# Ansible inventory created from ['netsims.yaml', 'package:topology-defaults.yml']
#
---
af:
  ipv4: true
  ipv6: true
bgp:
  advertise_loopback: true
  as: 100
  community:
    ebgp:
    - standard
    ibgp:
    - standard
    - extended
  ipv4: true
  ipv6: true
  neighbors:
  - as: 100
    ipv4: 10.0.0.1
    ipv6: 200:0:0:1::1
    name: R1
    type: ibgp
  - as: 200
    ifindex: 2
    ipv4: 10.1.0.6
    ipv6: 200:0:0:1::2
    name: R3
    type: ebgp
  next_hop_self: true
  router_id: 10.0.0.2
box: ceos:4.27.5M
clab:
  env:
    INTFTYPE: et
  kind: ceos
hostname: clab-basic-topology-R2
interfaces:
- clab:
    name: et1
  ifindex: 1
  ifname: Ethernet1
  ipv4: 10.1.0.2/30
  ipv6: 200::2/64
  linkindex: 1
  name: R2 -> R1
  neighbors:
  - ifname: Ethernet1
    ipv4: 10.1.0.1/30
    ipv6: 200::1/64
    node: R1
  ospf:
    area: 0.0.0.0
    network_type: point-to-point
    passive: false
  type: p2p
- clab:
    name: et2
  ifindex: 2
  ifname: Ethernet2
  ipv4: 10.1.0.5/30
  ipv6: 200:0:0:1::1/64
  linkindex: 2
  name: R2 -> R3
  neighbors:
  - ifname: Ethernet1
    ipv4: 10.1.0.6/30
    ipv6: 200:0:0:1::2/64
    node: R3
  role: external
  type: p2p
loopback:
  ipv4: 10.0.0.2/32
  ipv6: 200:0:0:2::1/64
mgmt:
  ifname: Management0
  ipv4: 192.168.121.102
  mac: 08-4F-A9-00-00-02
module:
- ospf
- bgp
ospf:
  af:
    ipv4: true
    ipv6: true
  area: 0.0.0.0
  router_id: 10.0.0.2
