# Ansible inventory created from ['netsims.yaml', 'package:topology-defaults.yml']
#
---
af:
  ipv4: true
  ipv6: true
bgp:
  advertise_loopback: true
  as: 200
  community:
    ebgp:
    - standard
    ibgp:
    - standard
    - extended
  ipv4: true
  ipv6: true
  neighbors:
  - as: 200
    ipv4: 10.0.0.3
    ipv6: 200:0:0:3::1
    name: R3
    type: ibgp
  next_hop_self: true
  router_id: 10.0.0.4
box: ceos:4.27.5M
clab:
  env:
    INTFTYPE: et
  kind: ceos
hostname: clab-basic-topology-R4
interfaces:
- clab:
    name: et1
  ifindex: 1
  ifname: Ethernet1
  ipv4: 10.1.0.10/30
  ipv6: 200:0:0:2::2/64
  linkindex: 3
  name: R4 -> R3
  neighbors:
  - ifname: Ethernet2
    ipv4: 10.1.0.9/30
    ipv6: 200:0:0:2::1/64
    node: R3
  ospf:
    area: 0.0.0.0
    network_type: point-to-point
    passive: false
  type: p2p
loopback:
  ipv4: 10.0.0.4/32
  ipv6: 200:0:0:4::1/64
mgmt:
  ifname: Management0
  ipv4: 192.168.121.104
  mac: 08-4F-A9-00-00-04
module:
- ospf
- bgp
ospf:
  af:
    ipv4: true
    ipv6: true
  area: 0.0.0.0
  router_id: 10.0.0.4
