# Ansible inventory created from ['netsims.yaml', 'package:topology-defaults.yml']
#
---
all: {}
as100:
  hosts:
    R1: {}
    R2: {}
as200:
  hosts:
    R3: {}
    R4: {}
custom_configs:
  hosts: {}
eos:
  hosts:
    R1:
      ansible_host: clab-basic-topology-R1
      id: 1
    R2:
      ansible_host: clab-basic-topology-R2
      id: 2
    R3:
      ansible_host: clab-basic-topology-R3
      id: 3
    R4:
      ansible_host: clab-basic-topology-R4
      id: 4
modules:
  hosts:
    R1: {}
    R2: {}
    R3: {}
    R4: {}
